approvedGitRepositories:
  - "**"

cacheFolder: .yarn/cache

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/echo-execute"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
