cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: 'https://yarnplugins.com/echo-execute'

yarnPath: .yarn/releases/yarn-4.17.1.cjs
