export const walletConnectMobileLinks = [
  'MetaMask',
  'Trust Wallet',
  'Zerion',
  'imToken',
  'Robinhood Wallet',
  'Rainbow',
  'Ledger Live',
  'Uniswap Wallet',
  '1inch Wallet',
  'Safe',
  'Ambire Wallet',
  'Unstoppable Domains',
  'Argent',
  'Omni',
  'MathWallet',
  'TokenPocket',
  'iToken Wallet',
  'Atomic',
  'Coin98',
  'CoolWallet',
  'Unstoppable Wallet',
  'Infinity Wallet',
  'Crypto.com | DeFi Wallet',
  'Guarda Wallet',
  'Trustee Wallet',
  'Rabby',
  'Tangem',
  'Coinbase Wallet',
  'Frame',
  'Blockchain.com',
  'Exodus',
  'ZenGo',
  'XDEFI Wallet',
  'Frontier',
  'OKX Wallet',
  'Brave Wallet',
  'Binance DeFi Wallet',
  'Fireblocks',
  'Phantom',
  'MEW wallet',
  'GameStop Wallet',
  'Opera Crypto Browser',
  'Taho',
];
