name: Check packages and deploy Demo App

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  check-all:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Corepack and set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build-packages

      - name: Run checks
        run: yarn check-packages

      - name: Publish demo app
        working-directory: apps/demo-react
        run: yarn run next build && yarn run next export
        env:
          BASE_PATH: /${{ github.event.repository.name }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          WALLETCONNECT_PROJECT_ID: ${{ vars.WALLETCONNECT_PROJECT_ID }}
          RPC_PROVIDER_URL_1: ${{ vars.RPC_PROVIDER_URL_1 }}
          RPC_PROVIDER_URL_17000: ${{ vars.RPC_PROVIDER_URL_17000 }}
          SUPPORTED_CHAINS: ${{ vars.SUPPORTED_CHAINS }}
          DEFAULT_CHAIN: ${{ vars.DEFAULT_CHAIN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'apps/demo-react/out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
