name: Publish to NPM

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  pre-publish:
    uses: ./.github/workflows/publish-dry-run.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: |
          corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: yarn build-packages

      - name: Verify provenance attestations & registry signatures of installed dependencies
        run: npm audit signatures

      - name: Audit dependencies for known vulnerabilities
        continue-on-error: true
        run: >-
          yarn workspaces foreach --all --no-private
          npm audit --recursive --environment production --no-deprecations --severity high

      - name: Authenticate in npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          echo "workspaces-update=false" >> .npmrc
          echo "provenance=true" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: yarn multi-semantic-release
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
